import { db } from "@/lib/db";
import { serialsFor, shortCodeFor } from "./serial";
import { refreshSampleJvResult } from "./match";

type Tx = Omit<typeof db, "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends">;

/**
 * Hands the experiment its short handle ("E7"), once. Monotonic per
 * organization and never reused, so a serial always means one experiment.
 */
export async function ensureShortCode(tx: Tx, experimentId: string): Promise<string> {
  const exp = await tx.experiment.findUniqueOrThrow({
    where: { id: experimentId },
    select: { shortCode: true, organizationId: true },
  });
  if (exp.shortCode) return exp.shortCode;

  const org = await tx.organization.update({
    where: { id: exp.organizationId },
    data: { nextShortNo: { increment: 1 } },
    select: { nextShortNo: true },
  });
  const shortCode = shortCodeFor(org.nextShortNo - 1);
  await tx.experiment.update({ where: { id: experimentId }, data: { shortCode } });
  return shortCode;
}

/**
 * Recomputes every sample's serial list for an experiment.
 *
 * Must be called after ANY change to the sample set. Because the serial is
 * derived from (shortCode, sample code), a sample regenerated by a test-plan
 * edit gets the same serial back — which is what lets orphaned measurements
 * re-attach themselves. Aliases a lab added by hand are preserved.
 */
export async function syncSampleSerials(tx: Tx, experimentId: string): Promise<void> {
  const shortCode = await ensureShortCode(tx, experimentId);
  const samples = await tx.sample.findMany({
    where: { experimentId },
    select: { id: true, code: true, instrumentCodes: true },
  });
  for (const s of samples) {
    // Anything not derivable from the current shortCode is a hand-added alias.
    const aliases = s.instrumentCodes.filter((c) => c !== serialsFor(shortCode, s.code)[0]);
    const next = serialsFor(shortCode, s.code, aliases);
    const same = next.length === s.instrumentCodes.length && next.every((c, i) => c === s.instrumentCodes[i]);
    if (!same) await tx.sample.update({ where: { id: s.id }, data: { instrumentCodes: next } });
  }
}

/**
 * Re-attaches measurements to an experiment's samples after the sample set was
 * rebuilt.
 *
 * Deleting samples sets JvMeasurement.sampleId to NULL but leaves the row
 * MATCHED, which would strand it: invisible on the sample AND absent from the
 * unmatched queue. Anything stranded is reset so the normal matcher can pick it
 * up again — by serial, so it lands on the same sample as before.
 */
export async function healOrphanedMeasurements(experimentId: string): Promise<number> {
  const stranded = await db.jvMeasurement.updateMany({
    where: { OR: [{ experimentId }, { experimentId: null }], sampleId: null, status: "MATCHED" },
    data: { status: "UNMATCHED", matchNote: "Sample set changed — waiting to be re-matched." },
  });
  return stranded.count;
}

/** Convenience for the places that rebuild samples outside a transaction. */
export async function refreshExperimentSerials(experimentId: string): Promise<void> {
  await syncSampleSerials(db, experimentId);
  await healOrphanedMeasurements(experimentId);
  const samples = await db.sample.findMany({ where: { experimentId }, select: { id: true } });
  for (const s of samples) await refreshSampleJvResult(s.id);
}
