import { normalizeSerial } from "./match";

/**
 * Instrument serials.
 *
 * Operators type a sample's serial into the instrument by hand, on a lab PC
 * with a Chinese IME, once per pixel. The full experiment code
 * ("2026-001-1-23-S5") is 17 characters and a typo magnet, so every experiment
 * also gets a short handle ("E7") and each sample answers to "E7-S5".
 *
 * The value is DERIVED, never stored as the source of truth for identity: a
 * sample regenerated by a test-plan edit gets the same serial back, so
 * measurements re-attach to it automatically.
 */
export function shortCodeFor(n: number): string {
  return `E${n}`;
}

export function sampleSerial(shortCode: string, sampleCode: string): string {
  if (!shortCode) return "";
  return normalizeSerial(`${shortCode}-${sampleCode}`);
}

/**
 * The serial list for a sample: the app-assigned one first, then any aliases a
 * lab has added for its own naming (kept, de-duplicated, normalized).
 */
export function serialsFor(shortCode: string, sampleCode: string, aliases: string[] = []): string[] {
  const primary = sampleSerial(shortCode, sampleCode);
  const out = primary ? [primary] : [];
  for (const alias of aliases) {
    const key = normalizeSerial(alias);
    if (key && !out.includes(key)) out.push(key);
  }
  return out;
}

/** Aliases are everything the app did not assign itself. */
export function aliasesOf(codes: string[], shortCode: string, sampleCode: string): string[] {
  const primary = sampleSerial(shortCode, sampleCode);
  return codes.filter((c) => c !== primary);
}
